### ISSUE TITLE
failing to parse EXIF after xml junk in GoPro 360 jpgs

### ISSUE THREAD

**Issue by dustin** [emmanueltouzery/hsexif#17]
I have been using this library to process media I've captured on GoPros.  I borrowed a GoPro Max and found that it I can't get to the (seemingly valid) EXIF data from within GoPro media.

I've attached an example here.  I don't quite know enough about EXIF itself, but it seems like there's another type of metadata that's in the file ahead of the normal EXIF data.

![max](https://user-images.githubusercontent.com/1779/77243103-404ffc80-6bc3-11ea-9fc8-8a1b9b11d2bd.jpg)

**Comment by emmanueltouzery** [comment]
Hi, I believe that's XMP - [adobe](https://wwwimages2.adobe.com/content/dam/acom/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2014-12/XMPSpecificationPart2.pdf), [wikipedia](https://photo.stackexchange.com/questions/47302/what-is-the-relationship-between-exif-and-xmp-are-they-interchangeable) not EXIF. I'm not sure how much work would it be to add XMP support. Doing so would also require additional dependencies, although it could be an optional feature of the library.

I would actually be interested in adding such a support, thank you for the sample file, but I probably won't do it short-term...

**Comment by dustin** [comment]
It's the exif after that bit I'm interested in.  I was hoping I could just
skip past it, but the parser wasn't happy with any tail.

**Comment by emmanueltouzery** [comment]
hmm indeed I see the `Exif` marker somewhat after the XML. Maybe something can be done after all. I'll read up a little on how to read files which combine XMP and EXIF like that, with the XMP first.

**Comment by emmanueltouzery** [comment]
right there are two ffe1 blocks which I did not expect. Seems like an easy fix, will look into it today.

**Comment by emmanueltouzery** [comment]
(got it to work, will push & release sometime today)

**Comment by dustin** [comment]
Oh awesome!  Thanks a lot!

**Comment by emmanueltouzery** [comment]
Hi, I've published 0.6.1.7 on hackage, this should fix the issue, let me know if it doesn't!

**Comment by dustin** [comment]
Seems to be working great.  Thanks for the quick turnaround and awesome library!
