### ISSUE TITLE
Problem reading gpsLatitudeRef and gpsLongitudeRef

### ISSUE THREAD

**Issue by wnke** [emmanueltouzery/hsexif#8]
There seems to be a problem reading the two tags mentioned above, making the result of getGpsLatitudeLongitude wrong.

Here is the result from reading a jpg file:

fromList [(dateTimeOriginal,06:08:2015 14:58:1),(exifImageWidth,640),(exifImageHeight,512),(make,FLI),(model,Tau 2 64),(software,AscTec Navigator by Ascending Technologies Gmb),(exifIfdOffset,132),(gpsTagOffset,194),**(gpsLatitudeRef,)**,(gpsLatitude,[(38,1),(10,1),(426892,10000)]),**(gpsLongitudeRef,)**,(gpsLongitude,[(7,1),(12,1),(395913,10000)]),(gpsAltitudeRef,0),(gpsAltitude,267859/1000),(gpsImgDirectionRef,),(gpsImgDirection,6959/100),(gpsMapDatum,WGS-84 ellipsoi),(Unknown tag, location: GpsSubIFD, value: 0xd000,-4968/100),(Unknown tag, location: GpsSubIFD, value: 0xd001,0/100)]

As you can see both Refs are empty. The same jpg image is working fine using python's exifread, so I don't think the problem is the image.

Kind regards,
João

**Comment by emmanueltouzery** [comment]
There is a test for that, it should work.. can you attach a test image reproducing the problem?

**Comment by emmanueltouzery** [comment]
Hmmm although i don't remember specifically about the "ref" tags.

**Comment by wnke** [comment]
This tags are very important as they set the 'minus' on the coordinates.

The image is attached.

Thanks for your attention,
João

**Comment by emmanueltouzery** [comment]
Ok thanks, i'll look into it through the week-end. Note that i checked and I make use of it in the publicly-exported higher-level `getGpsLatitudeLongitude` which may be of use to you:

https://hackage.haskell.org/package/hsexif-0.6.0.4/docs/Graphics-HsExif.html#v:getGpsLatitudeLongitude

**Comment by emmanueltouzery** [comment]
Hmm otherwise i think you attached the image to an email reply on github but it didn't make it to the bug tracker (not sure they support attachments). Maybe you can put it online somewhere and paste the link here?

**Comment by wnke** [comment]
Link to the file:
https://drive.google.com/file/d/0B_uhVHNCTbA9MTdDUnFoUHR5bkE/view?usp=sharing

Thanks,
João

**Comment by emmanueltouzery** [comment]
Right. There is a bug definitely. I didn't notice because I coded:

    let signedLatDec = if latRef == "S" then -latDec else latDec
    let signedLongDec = if longRef == "W" then -longDec else longDec

And both numbers are positive for me. But the longitude is negative for you and now the bug shows. I'll fix it ASAP.

**Comment by emmanueltouzery** [comment]
hmm it's a little more than that, because it does work 100% properly for the test gps file that I have.

**Comment by emmanueltouzery** [comment]
The issue turned out to be with nul terminations. In all the EXIF files I'd seen so far, the "component count" for text entries was including the nul termination, but in this file it wasn't. `hsexif` now supports both configurations. I've released 0.6.0.5 on hackage with the fix, please reopen if that doesn't fix the issue, and thank you for the report!

**Comment by wnke** [comment]
Thanks! :)
